"""
corridor_planner.py
-------------------
Corridor (linear) flight-route generator for 2D mapping.

Given a centre line and a corridor half-width (buffer), it produces a set of
parallel passes that follow the line and cover the corridor, then returns the
waypoints the drone flies. Output matches grid_planner.generate_flight_grid
((waypoints, spacing) with waypoints as (lon, lat) in WGS84), so the rest of the
FlyPath pipeline (terrain follow, mission splitting, the WPML writer, stats and
export) is reused unchanged.

Design notes
------------
* Nadir (-90 deg) only, exactly like 2D mapping. No heading/gimbal changes.
* Parallel passes are generated by offsetting the centre line (QgsGeometry.
  offsetCurve), so they follow every curve. This deliberately avoids the
  buffer-into-polygon-then-grid approach, which gave uneven waypoint spacing.
* Number of passes is derived automatically from the corridor width, camera
  footprint and side overlap (see corridor_geometry.compute_pass_offsets).
* Pure maths (sampling, offsets, snaking) lives in corridor_geometry.py and is
  unit-tested without QGIS.

This module only READS from grid_planner (the shared _utm_crs_for helper); it
does not modify the 2D-mapping code.
"""

from qgis.core import (
    Qgis,
    QgsGeometry,
    QgsPointXY,
    QgsCoordinateReferenceSystem,
    QgsCoordinateTransform,
    QgsProject,
    QgsWkbTypes,
)

from .grid_planner import _utm_crs_for
from .corridor_geometry import (
    sample_polyline, compute_pass_offsets, snake_passes, polyline_length,
)

try:
    _LineGeometry = QgsWkbTypes.GeometryType.LineGeometry
except AttributeError:                       # pragma: no cover - older QGIS
    _LineGeometry = getattr(QgsWkbTypes, 'LineGeometry')

# offsetCurve join style. Miter keeps corners sharp (following the centre line's
# angles) instead of rounding them, which also avoids the arc of extra vertices a
# round join adds at every corner - so the passes carry fewer waypoints. It needs
# the Qgis.JoinStyle enum (an int raises TypeError), scoped for Qt6 with a getattr
# fallback for older QGIS.
try:
    _JOIN_MITER = Qgis.JoinStyle.Miter
except AttributeError:                       # pragma: no cover - older QGIS
    _JOIN_MITER = getattr(Qgis, 'JoinStyleMiter')
_OFFSET_SEGMENTS = 8
_MITER_LIMIT = 2.0


def _line_parts_xy(geom):
    """Return a Line/MultiLine geometry as a list of parts, each a list of
    (x, y) tuples. Branches on isMultipart() so it is correct on QGIS 3 and 4
    (asPolyline()/asMultiPolyline() raise on the wrong type)."""
    if geom is None or geom.isEmpty():
        return []
    if geom.isMultipart():
        return [[(p.x(), p.y()) for p in part] for part in geom.asMultiPolyline()]
    return [[(p.x(), p.y()) for p in geom.asPolyline()]]


def _offset_coords(coords, distance):
    """Offset a polyline (list of (x, y) in metres) sideways by `distance` using
    QGIS's offsetCurve. Returns the offset polyline as a list of (x, y), or None
    if the offset fails or collapses (which can happen on very sharp inner
    curves). On self-intersection offsetCurve may split into several parts; the
    longest part is returned.
    """
    line = QgsGeometry.fromPolylineXY([QgsPointXY(x, y) for x, y in coords])
    try:
        off = line.offsetCurve(distance, _OFFSET_SEGMENTS, _JOIN_MITER, _MITER_LIMIT)
    except Exception:                        # offsetCurve can raise on bad geometry
        return None
    if off is None or off.isEmpty() or off.isNull():
        return None
    parts = _line_parts_xy(off)
    parts = [p for p in parts if len(p) >= 2]
    if not parts:
        return None
    parts.sort(key=polyline_length, reverse=True)
    return parts[0]


def generate_corridor_route(line_geom, line_crs, altitude_m, shot_spacing_m,
                            side_overlap, buffer_m, drone_specs,
                            densify_spacing=None):
    """Generate a corridor flight route from a centre line.

    Parameters
    ----------
    line_geom      : QgsGeometry  - corridor centre line (Line or MultiLine, any CRS)
    line_crs       : QgsCoordinateReferenceSystem
    altitude_m     : float        - AGL flight altitude in metres
    shot_spacing_m : float        - along-track photo spacing (speed x interval)
    side_overlap   : float        - 0.0-0.99 (sets spacing between parallel passes)
    buffer_m       : float        - corridor half-width: distance covered EACH SIDE
                                    of the centre line (total width = 2 x buffer_m)
    drone_specs    : dict         - {focal_length_mm, sensor_width_mm}
    densify_spacing: float | None - full-automatic photo spacing. When set, every
                                    pass is resampled at this spacing (a waypoint
                                    per photo). When None (semi-automatic), the
                                    passes keep their geometry vertices only and
                                    the camera fires by interval capture.

    Returns
    -------
    (waypoints, sample_spacing_m)
    waypoints       : list of (lon, lat) in WGS84
    sample_spacing_m: float, the along-track photo/interval spacing (for stats)

    Raises
    ------
    ValueError if inputs are invalid or no waypoints are produced.
    """
    if altitude_m <= 0:
        raise ValueError('Altitude must be greater than 0.')
    if not (0.0 <= side_overlap < 1.0):
        raise ValueError('Side overlap must be between 0% and 99%.')
    if not drone_specs:
        raise ValueError('No drone specifications provided.')
    if line_geom is None or line_geom.isEmpty():
        raise ValueError('Draw or select a corridor centre line first.')
    if QgsWkbTypes.geometryType(line_geom.wkbType()) != _LineGeometry:
        raise ValueError('Corridor mapping needs a line geometry.')

    # 1 - reproject to WGS84 to locate the UTM zone, then to metric UTM
    wgs84 = QgsCoordinateReferenceSystem('EPSG:4326')
    to_wgs84 = QgsCoordinateTransform(line_crs, wgs84, QgsProject.instance())
    line_wgs = QgsGeometry(line_geom)
    line_wgs.transform(to_wgs84)
    centroid = line_wgs.centroid().asPoint()
    utm_crs = _utm_crs_for(centroid.x(), centroid.y())
    to_utm = QgsCoordinateTransform(line_crs, utm_crs, QgsProject.instance())
    from_utm = QgsCoordinateTransform(utm_crs, wgs84, QgsProject.instance())
    line_utm = QgsGeometry(line_geom)
    line_utm.transform(to_utm)

    # 2 - footprint, line spacing (across track) and sample spacing (along track)
    fl = drone_specs['focal_length_mm']
    sw = drone_specs['sensor_width_mm']
    footprint_across = altitude_m * sw / fl
    line_spacing = max(footprint_across * (1.0 - side_overlap), 0.5)
    sample_spacing = max(densify_spacing or shot_spacing_m, 0.5)

    # Full-automatic (densify_spacing set) places a waypoint at every photo, so
    # the passes are resampled at the photo spacing. Semi-automatic relies on the
    # pilot's interval capture, so it only needs a waypoint at each geometry
    # vertex (the points the drone must fly through) - dense on curves, sparse on
    # straights - mirroring 2D semi. The camera fires by interval in between.
    full_auto = densify_spacing is not None

    # 3 - one set of parallel offsets, applied to each part of the centre line
    offsets = compute_pass_offsets(buffer_m, line_spacing, footprint_across)

    waypoints = []
    for part_coords in _line_parts_xy(line_utm):
        if len(part_coords) < 2:
            continue
        passes = []
        for off in offsets:
            coords = (part_coords if abs(off) < 1e-9
                      else _offset_coords(part_coords, off))
            if coords and len(coords) >= 2:
                pass_pts = (sample_polyline(coords, sample_spacing) if full_auto
                            else list(coords))
                passes.append(pass_pts)
        route_utm = snake_passes(passes)
        for x, y in route_utm:
            pt = from_utm.transform(QgsPointXY(x, y))
            waypoints.append((pt.x(), pt.y()))          # (lon, lat)

    if not waypoints:
        raise ValueError(
            'The corridor produced no waypoints.\n'
            'Check that the line has length and the buffer is greater than 0.'
        )
    return waypoints, sample_spacing
